Repository myyrakle/rupring, pull requests merged in 2024-09, with the labels that each got.

#146 fix: RouteName and Handler Name shoulde be camel case because this is struct
  rupring_macro/src/lib.rs
Labels: enhancement

#148 [#144] 응답 압축 구현
  application.properties
  rupring/Cargo.toml
  rupring/src/application_properties.rs
  rupring/src/core/boot.rs
  rupring/src/core/mod.rs
  rupring/src/header.rs
  rupring/src/lib.rs
  rupring/src/response.rs
Labels: feature, breaking

#153 [#149] application.properties 문서화
  rupring/src/application_properties.rs
  rupring/src/lib.rs
Labels: documentation
